### ISSUE TITLE
Wrong Ruby version used during test invocation with Rbenv + ZSH + Spacemacs

### ISSUE THREAD

**Issue by Dangeranger** [pezra/rspec-mode#166]
## Problem:

When invoking `rspec-verify-all` from within any spec file using the keybinding <kbd>CTRL</kbd>+<kbd>c</kbd> , <kbd>,</kbd>, <kbd>a</kbd> instead of using the Ruby binary version specified in the `.ruby-version` located at the project root, `rspec-mode` is invoking `rspec` with the default system ruby instead.

## Expected behavior:

`rspec-mode` was expected to invoke `rspec` with the Ruby version installed via `ruby-build` at `/Users/username/.rbenv/versions/2.2.3/bin/ruby`.

## Error message:

```sh
-*- mode: rspec-compilation; default-directory: "~/Dev/projects/some-project/" -*-
RSpec Compilation started at Tue Aug 29 11:52:40

bundle exec rspec --options /Users/username/Dev/projects/some-project/.rspec /Users/username/Dev/projects/some-project/spec
/Library/Ruby/Site/2.0.0/rubygems.rb:243:in `bin_path': can't find gem bundler (>= 0) (Gem::GemNotFoundException)
    from ./bin/bundle:3:in `<main>'

RSpec Compilation exited abnormally with code 1 at Tue Aug 29 11:52:40
```

## Environment notes:

```yaml
OS: MacOS Sierra 10.12.6 (16G29)
rbenv version: 1.0.0
ruby-build version: 20170726
emacs version: GNU Emacs 25.1.1 (x86_64-apple-darwin14.5.0, Carbon Version 157 AppKit 1348.17)
spacemacs version:   0.200.9@25.1.1 (spacemacs)
```
Thanks for your help 👍
